### ISSUE TITLE
Add translation (il8n) support

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#1]
**Adding international translation support with getText.**

People could create languages files easily and change languages on UkeGeeks.

**Comment by bloodybowlers** [comment]
Hum... given the size of the project, maybe a simple json file would be enough :)

The json file can be loaded php side and js side, so perfect !

**Comment by bloodybowlers** [comment]
Added translation support. Currently English and French.

**Comment by louis-coding** [comment]
1. Some tooltips are still missing in the language file (e.g. on the chord editor on the up/down arrows)
2. I would have a DE.json available, but unfortunately I can't fork your fork and create a pull request
3. could you also add an optional per-user language setting? (Of course only for logged in users, if not set the site default is used)

**Comment by Louis-coding-UGNG** [comment]
Managed to get around the limitations of Git by creating a new account with no fork of Buz's original :)
Created a pull request now
