### ISSUE TITLE
Rename the Config.php to Config.php.example

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#11]
Rename the Config.php to Config.php.example, so that when you modify the config file, it won't lead to "changes to be committed" in git tree. (@acelan)

**Comment by acelan** [comment]
\o/

**Comment by bloodybowlers** [comment]
Fixed in a43f32bbb8f63b350dce68649152e84b5edc8c72 (+ 7f84b8cfe5a38384ff77f3b834c1e2d5e0082fab)

**Comment by Louis-coding-UGNG** [comment]
Didn't you want to rename it to config.php_example? If so, why is it still config_example.php?
