### ISSUE TITLE
Multiple songbook sorting mode (by title, artist, ...)

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#13]
Multiple songbook sorting mode (by title, artist, ...)

**Comment by bloodybowlers** [comment]
Waiting for **Category (x_UGNG_category)** to be added, then I'll add this.

**Comment by Louis-coding-UGNG** [comment]
even in #68 the artist sorting is case-sensitive: `{artist: The Beatles}` and `{artist: traditional}` are listed as two seperate "T" sections.
IMHO all sorting criteria should not be case-sensitive. It might be debatable to (optionally) omit prefixes like "The" or "A", but there should not be a difference between "the" and "The".

**Comment by bloodybowlers** [comment]
You are right, I'll take a look at that and fix it.
