### ISSUE TITLE
Add an auto scroll button

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#21]
Original issue by @ptitpoulpe : 

An auto scroll bouton like in some tablature website.
(eg: http://tabs.ultimate-guitar.com/r/rihanna/umbrella_acoustic_ukulele_crd.htm)

**Comment by louis-coding** [comment]
or like on Jim's Songbook, e.g. https://ozbcoz.com/Songs/song.php?ID=4426,soprano

**Comment by bloodybowlers** [comment]
I can't decide between : 

- below the chords (horizontally)
- to the right of the screen (vertically, like a lot of tabs website)

**Comment by bloodybowlers** [comment]
Added in b583e2c9a2b0731e8c02feba638e9c847a2ea376
