### ISSUE TITLE
french text in lang/EN.json

### ISSUE THREAD

**Issue by louis-coding** [bloodybowlers/UkeGeeks-ng#22]
https://github.com/bloodybowlers/UkeGeeks-ng/blob/6c8789432a4cdf934e5c1d0c8a837b034cb15706/lang/EN.json#L43
https://github.com/bloodybowlers/UkeGeeks-ng/blob/6c8789432a4cdf934e5c1d0c8a837b034cb15706/lang/EN.json#L59

unfortunately I can only recognize French, not translate it...

**Comment by bloodybowlers** [comment]
Ooooops, will fix it shortly, sorry :p

**Comment by bloodybowlers** [comment]
Done. 3d9348806550e24de4028612c317bbab9cf2a828
