### ISSUE TITLE
Integrated Chord finder

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#3]
Integrated Chord finder

**Comment by louis-coding** [comment]
Based on internal definitions (ukeGeeks.definitions.sopranoUkuleleGcea.js)?
Could basically be a nicely formatted output of the definitions file as a first version, a kind of chord sheet if you like. Or a dropdown selection per root note...

**Comment by bloodybowlers** [comment]
Something [like that one](http://ukegeeks.com/tools/chord-finder.htm).
Indeed it uses the internal definitions.

**Comment by bloodybowlers** [comment]
Added in 9aba80869f310a9088725784f1a1494885ee1586
