### ISSUE TITLE
make lang tag in views dynamic or delete it

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#35]
all views .php have a language statically defined like here:
https://github.com/bloodybowlers/UkeGeeks-ng/blob/ef07131e4852916991f18751f0a182e91e12db91/ugsphp/views/login.php#L8

After successful closure of #1 this should either be deleted or adapted dynamically to the user preference (if set in config) or site defualt as set in config file.
Something like 
`<html lang="<?php echo ($model->Lang); ?>">`
where Lang should be defined in  ugsphp/viewmodels/_base_Vm.php in the __base_Vm_ class  like e.g. `public $Lang = Config::Lang;`

**Comment by bloodybowlers** [comment]
You are right, I removed this useless tag fd0b8d2cd7e75890d93c0a9ae0b9b7966623c342
