### ISSUE TITLE
Mod_rewrite not redirecting as intended if subdirectory is not set to /

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#37]
Mod_rewrite not redirecting as intended if subdirectory is not set to /

**Comment by bloodybowlers** [comment]
I think changing the RewriteBase directive to the subidr should work ?

**Comment by Louis-coding-UGNG** [comment]
just set up a test instance on https://ng.4str.in/test and it doesn't work, When I try to edit a song I only get "The requested URL /music.php was not found on this server."
`const Subdirectory = '/test/';`
`RewriteBase /test` (trailing slash doesn't make a difference)

**Comment by Louis-coding-UGNG** [comment]
OK, it's time to bash my head against the wall.....
Seems the leading slash before"music.php" in the _RewriteRule_ must be removed to allow _RewriteBase_ to kick in:
old `RewriteRule ^songbook/?$ /music.php?action=songbook [L,QSA]`
should become `RewriteRule ^songbook/?$ music.php?action=songbook [L,QSA]`

**Comment by Louis-coding-UGNG** [comment]
As already mentioned on https://github.com/bloodybowlers/UkeGeeks-ng/pull/48#issuecomment-520804029:

>After deleting a song it redirect to the "song not found" page.

This doesn't seem to be a rewrite problem but rather a matter of https://github.com/bloodybowlers/UkeGeeks-ng/blob/f16cd68ad1b1a2e1329ea758eababb5b0ebac68e/src/js/editor/ugsEditorPlus.deleteSong.js#L106
where the location should simply be `'./'` instead
(see https://github.com/bloodybowlers/UkeGeeks-ng/issues/17#issuecomment-520144440)

Works at least for me in root and subdirectory installations.

**Comment by bloodybowlers** [comment]
I see.  
The thing is, when I tested your PR, you didn't include the ./ fix. Instead you reverterd a change (here : 38a1226) and you made this change 862c2dc.  

Would you mind making a PR specifically for the htaccess change ? (without any other change or feature) pls ? If you do so, maybe include the "./" redirect fix too, if it works in your tests ?

**Comment by Louis-coding-UGNG** [comment]
Admittedly I was a bit too quick and committed the change before testing, so I had to revert it somehow after it failed...

PR #57 includes both updates now.
