### ISSUE TITLE
Integrated reverse chord finder

### ISSUE THREAD

**Issue by bloodybowlers** [bloodybowlers/UkeGeeks-ng#4]
Integrated reverse chord finder

**Comment by louis-coding** [comment]
Something like that?

1. let user create chord shape (e.g. in chord editor)
2. run it against definitions in ukeGeeks.definitions.sopranoUkuleleGcea.js
3. return chord name(s) if found

**Comment by bloodybowlers** [comment]
Added in 9aba80869f310a9088725784f1a1494885ee1586
