### ISSUE TITLE
include default values for reference in settings.js

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#40]
I'm already behind you again with my fork and haven't added a new branch to pull....
Nevertheless I thought it would be nice to have the default values mentioned in _settings.js_ like I did here: https://github.com/Louis-coding-UGNG/UkeGeeks-ng/commit/170d97aec642f9f2fd5cc97423f340e87e050110

**Comment by bloodybowlers** [comment]
Sure, I'll do it and commit after your DE translation PR (to avoid conflict)

**Comment by bloodybowlers** [comment]
And also, **don't forget to change soprano to standard in your own settings.js** 
I removed all soprano references from the source code in commit aea0785bcd3f0853d0d6cfc0d0014b993e0154aa
