### ISSUE TITLE
Override settings.js values per song

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#47]
Perhaps slightly related to #18 

Would be great to have a possibility to override some standard layout settings for individual songs only. I am specifically thinking of the _diagramPosition_ and _lyricStyle_, in my use case I would like to switch from diagrams on left to diagrams on top for a single song only (it contains 11 chords)

 - [x] x_UGNG_diagramPosition
 - [x] x_UGNG_lyricStyle
 - [x] x_UGNG_hideChordEnclosures

**Comment by bloodybowlers** [comment]
Yep, good idea. I think the meta tag with some **x_UGNG_*** directives is the way to go 👍 

Edit : using a custom directive starting with x_ as in the [chordPro spec](https://www.chordpro.org/chordpro/ChordPro-Directives.html#custom-extensions)

(related to #18)

**Comment by bloodybowlers** [comment]
Added **x_UGNG_diagramPosition**.

**Comment by bloodybowlers** [comment]
**lyricStyle** added in d6aec322b8e98d63aad189ca4a60ce906fa72258

Hmmm, I'm wondering why one would need to **hide chord enclosures** for a specific song ?

**Comment by bloodybowlers** [comment]
**diagramPosition** and **lyricStyle** are added.

I'm closing this issue.  
Of course re-open if more customization needed.

**Comment by Louis-coding-UGNG** [comment]
>Hmmm, I'm wondering why one would need to hide chord enclosures for a specific song ?

When you change the layout from chords above to chords inline it might help to add the enclosures for better visibility (and v.v. the enclosures are not needed when chords are above the text)
Example:
>[C]Wise [Em]men [Am]say only [F]fools [C]rush [G]in

vs
> C Wise  Em men  Am say only  F fools  C rush  G in

Personally I would even say that inline chords should always have enclosures by default whereas chords above should never be enclosed... (Exept when using the _just black_ theme where the chords are always inverted anyway - but that could be handled by css setting the enclosures to _display: none_)

**Comment by Louis-coding-UGNG** [comment]
One minor improvement wish regarding the _x_UGNG_diagramPosition_ which I just tested:
Adding the tag and updating the song works fine and as expected 👍 
But to revert this back to defined site default I have to 
1. deactivate/remove the tag from song source, 
2. save it, 
3. close the tag and 
4. open it again. 

Would be nicer if simply pressing "update" or saving the song would immediately update the diagram position. Once the tag is in the song source I can update it to whatever valid value I want and it immediately updates the view on button press - only removing the tag doesn't automatically revert to site default with a single click.
(Probably valid for the others as well, haven't tested the full set.)

**Comment by bloodybowlers** [comment]
> Personally I would even say that inline chords should always have enclosures by default whereas chords above should never be enclosed...

That's interesting. If we want to do that, we need to find a solution for the current config settings that show/hide enclosures. It would need 3 positions ? AUTO, FORCE ON, FORCE OFF ?

Another solution would be to simply have an AUTO option. No config settings. I don't know...

**Comment by Louis-coding-UGNG** [comment]
For me personally, automatic would be sufficient - but that's just me.
Any chance to solve it via css with _:before_ and _:after_ elements for the enclosures?
AFAIK the inline chords css is `.ugsInline .ugsChords code` whereas the above chords are simply `.ugsChords code`

I don't know either....
Perhaps just park this as a feature request for a future milestone....
For the time being it would be sufficient to have a manual override possibility.

**Comment by bloodybowlers** [comment]
> One minor improvement wish regarding the _x_UGNG_diagramPosition_ which I just tested:
> Adding the tag and updating the song works fine and as expected 👍
> But to revert this back to defined site default I have to
> 
> 1. deactivate/remove the tag from song source,
> 2. save it,
> 3. close the tag and
> 4. open it again.
> 
> Would be nicer if simply pressing "update" or saving the song would immediately update the diagram position. Once the tag is in the song source I can update it to whatever valid value I want and it immediately updates the view on button press - only removing the tag doesn't automatically revert to site default with a single click.
> (Probably valid for the others as well, haven't tested the full set.)

Yes, valid for the others. Currently, there is no "default" fallback inside the editor. Fallback happen if you load another song.  
To do it, we would need to track if the tag is present in the song, and then, if it is removed (with or without saving). It's pretty tedious to do, but it's doable.

Feel free to open a new issue for this specific point.
