### ISSUE TITLE
pls delete src/js/editor/mergeJS.bat

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#55]
https://github.com/bloodybowlers/UkeGeeks-ng/blob/c4756432ab47e74886ade6e8a56f3a1901ed9cc6/src/js/editor/mergeJS.bat#L1

It doesn't work and should never have been included in the code anyway.....

Rather add the two .php files added in https://github.com/Louis-coding-UGNG/UkeGeeks-ng_c475643/tree/merge_commands - they do the same like your mergeJS.sh scripts, just in php

**Comment by bloodybowlers** [comment]
Sure, no problem.

**Comment by bloodybowlers** [comment]
Done.
