### ISSUE TITLE
Sorting of non-ASCII characters

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#71]
In my collection I have a song with `{title: Über den Wolken}` - the Ü only shows as � on the title-sorted songbook page.

Is that just a matter of the selected font or a real issue?

**Comment by bloodybowlers** [comment]
It is indeed a **font** issue.

Tested on my install (using Jelly MONO theme) and the Ü is perfectly displayed in the songlist and in the song editor.

**Comment by Louis-coding-UGNG** [comment]
OK, I'll have a closer look then at the loaded (or not loaded) fonts.

Thx for checking
