### ISSUE TITLE
block or inline-block?

### ISSUE THREAD

**Issue by Louis-coding-UGNG** [bloodybowlers/UkeGeeks-ng#75]
This doesn't really look like correct css to me.....
https://github.com/bloodybowlers/UkeGeeks-ng/blob/b4446703c7841f53204520b9a2d69ba872595632/css/ukeGeeks.music.css#L60

and it is contradicting the previous declaration of .ugs-grouped - should it be _display: block_ or _display: inline-block_?

**Comment by bloodybowlers** [comment]
It is valid css ([see here](https://www.w3schools.com/css/css_inline-block.asp)).  
IIrc, it was used because block or inline alone weren't enough (no top respect for example).

Feel free to re-open the issue if you think the display is broken anyway.
